#!/bin/sh
set -e

SOUNDBYTE_API_DB_USER="${SOUNDBYTE_API_DB_USER:=soundbyte}"
SOUNDBYTE_API_DB_PASSWORD="${SOUNDBYTE_API_DB_PASSWORD:=password}"
SOUNDBYTE_API_DB_NAME="${SOUNDBYTE_API_DB_NAME:=io_soundbyte_api}"

psql -v ON_ERROR_STOP=0 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${SOUNDBYTE_API_DB_USER} WITH PASSWORD '${SOUNDBYTE_API_DB_PASSWORD}';
EOSQL

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE ${SOUNDBYTE_API_DB_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${SOUNDBYTE_API_DB_NAME} TO ${SOUNDBYTE_API_DB_USER};
    ALTER USER ${SOUNDBYTE_API_DB_USER} WITH SUPERUSER;
EOSQL